### ISSUE TITLE
Daca radius e nr intreg, inmultirea la 2 va fi tot intreg, nu e nevoie de convertit in double

### ISSUE THREAD

**Issue by asersun** [ValeriaP99/JavaTasks#3]
https://github.com/ValeriaP99/JavaTasks/blob/0d463dee1d72d483a215ec31eefffc959b81ce83/src/md/pentalog/tasks_part1/chapter2/Ex28.java#L16

**Comment by ValeriaP99** [comment]
Rezolvat!
