### ISSUE TITLE
De ce nu folosesti direct valoarea variabilei, ea este aici vizibila?

### ISSUE THREAD

**Issue by asersun** [ValeriaP99/JavaTasks#9]
https://github.com/ValeriaP99/JavaTasks/blob/10dd7a6a80ffcd03647c3dceaac6ba6895fd9c3c/src/md/pentalog/tasks_part1/chapter3/Ex16/HeartRates.java#L77

**Comment by ValeriaP99** [comment]
Rezolvat!
